# Generated by Django 4.1.5 on 2023-01-12 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_launch_date', models.DateField(blank=True, null=True)),
                ('create_project_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'all projects',
            },
        ),
    ]
