# Generated by Django 4.1.4 on 2023-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='small_description',
            field=models.TextField(default='deafult'),
            preserve_default=False,
        ),
    ]
