# Generated by Django 4.1.5 on 2023-01-22 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectApp', '0002_project_small_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_description',
            field=models.CharField(max_length=100),
        ),
    ]
