# Generated by Django 4.1.5 on 2023-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_project_userid_alter_project_small_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='userID',
        ),
        migrations.AddField(
            model_name='project',
            name='total_fund',
            field=models.IntegerField(default=0),
        ),
    ]
