# Generated by Django 4.1.5 on 2023-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_remove_project_small_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='small_description',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
